

import {ref} from 'vue'
export const useColumn = () => {
    let columList = ref(

        [
            {
              "createTime": "2024-07-08 11:17:37",
              "createUser": "吴斌",
              "updateTime": "2024-07-08 11:21:26",
              "updateUser": "吴斌",
              "belongUserId": "1182830742988787712",
              "belongDeptId": "1810140005514932226",
              "tenantId": "7",
              "channelId": "1810151224044093441",
              "channelIcon": "",
              "channelName": "YouTube",
              "channelCode": "001",
              "sortNum": 0,
              "channelSummary": "",
              "waterMarkImg": "",
              "waterMarkLocation": "",
              "waterMarkScale": 30,
              "waterMarkAlpha": 100,
              "parentChannelId": "-1",
              "parentChannelIds": null,
              "parentChannelNames": null,
              "channelLevel": 0,
              "extFieldsList": [],
              "appId": "1384429363007430656",
              "auditId": null,
              "appShowFlag": 0,
              "auditFlag": 0,
              "commentAuditFlag": 0,
              "domainName": null,
              "templateIds": "",
              "toggle":true,
              "children": [
                {
                  "createTime": "2024-07-08 11:19:44",
                  "createUser": "吴斌",
                  "updateTime": "2024-07-08 11:23:08",
                  "updateUser": "吴斌",
                  "belongUserId": "1182830742988787712",
                  "belongDeptId": "1810140005514932226",
                  "tenantId": "7",
                  "channelId": "1810151755698864130",
                  "channelIcon": "",
                  "channelName": "EICC",
                  "channelCode": "0000",
                  "sortNum": 0,
                  "channelSummary": "",
                  "waterMarkImg": "",
                  "waterMarkLocation": "",
                  "waterMarkScale": 30,
                  "waterMarkAlpha": 100,
                  "parentChannelId": "1810151224044093441",
                  "parentChannelIds": "1810151224044093441",
                  "parentChannelNames": "YouTube",
                  "channelLevel": 1,
                  "extFieldsList": [],
                  "appId": "1384429363007430656",
                  "auditId": null,
                  "appShowFlag": 0,
                  "auditFlag": 0,
                  "commentAuditFlag": 0,
                  "domainName": null,
                  "templateIds": "",
                  "children": null,
                  "extFields": "[]",
                  "publishArticleFlag": 1,
                  "imortantFlag": 0,
                  "keywords": "",
                  "channelGrade": 0
                },
                {
                  "createTime": "2024-07-08 11:20:32",
                  "createUser": "吴斌",
                  "updateTime": "2024-07-08 11:23:17",
                  "updateUser": "吴斌",
                  "belongUserId": "1182830742988787712",
                  "belongDeptId": "1810140005514932226",
                  "tenantId": "7",
                  "channelId": "1810151958401187842",
                  "channelIcon": "",
                  "channelName": "SeeTheElephant",
                  "channelCode": "0001",
                  "sortNum": 0,
                  "channelSummary": "",
                  "waterMarkImg": "",
                  "waterMarkLocation": "",
                  "waterMarkScale": 30,
                  "waterMarkAlpha": 100,
                  "parentChannelId": "1810151224044093441",
                  "parentChannelIds": "1810151224044093441",
                  "parentChannelNames": "YouTube",
                  "channelLevel": 1,
                  "extFieldsList": [],
                  "appId": "1384429363007430656",
                  "auditId": null,
                  "appShowFlag": 0,
                  "auditFlag": 0,
                  "commentAuditFlag": 0,
                  "domainName": null,
                  "templateIds": "",
                  "children": null,
                  "extFields": "[]",
                  "publishArticleFlag": 1,
                  "imortantFlag": 0,
                  "keywords": "",
                  "channelGrade": 0
                }
              ],
              "extFields": "[]",
              "publishArticleFlag": 1,
              "imortantFlag": 0,
              "keywords": "",
              "channelGrade": 0
            },
            {
              "createTime": "2024-07-08 11:21:17",
              "createUser": "吴斌",
              "updateTime": "2024-07-08 11:21:17",
              "updateUser": "吴斌",
              "belongUserId": "1182830742988787712",
              "belongDeptId": "1810140005514932226",
              "tenantId": "7",
              "channelId": "1810152148695187457",
              "channelIcon": "",
              "channelName": "TikTok",
              "channelCode": "002",
              "sortNum": 0,
              "channelSummary": "",
              "waterMarkImg": "",
              "waterMarkLocation": "",
              "waterMarkScale": 30,
              "waterMarkAlpha": 100,
              "parentChannelId": "-1",
              "parentChannelIds": null,
              "parentChannelNames": null,
              "channelLevel": 0,
              "extFieldsList": [],
              "appId": "1384429363007430656",
              "auditId": null,
              "appShowFlag": 0,
              "auditFlag": 0,
              "commentAuditFlag": 0,
              "domainName": null,
              "templateIds": "",
              "toggle":false,
              "children": [
                {
                  "createTime": "2024-07-08 11:22:41",
                  "createUser": "吴斌",
                  "updateTime": "2024-07-08 11:23:29",
                  "updateUser": "吴斌",
                  "belongUserId": "1182830742988787712",
                  "belongDeptId": "1810140005514932226",
                  "tenantId": "7",
                  "channelId": "1810152498613387266",
                  "channelIcon": "",
                  "channelName": "see_the_elephant",
                  "channelCode": "0100",
                  "sortNum": 0,
                  "channelSummary": "",
                  "waterMarkImg": "",
                  "waterMarkLocation": "",
                  "waterMarkScale": 30,
                  "waterMarkAlpha": 100,
                  "parentChannelId": "1810152148695187457",
                  "parentChannelIds": "1810152148695187457",
                  "parentChannelNames": "TikTok",
                  "channelLevel": 1,
                  "extFieldsList": [],
                  "appId": "1384429363007430656",
                  "auditId": null,
                  "appShowFlag": 0,
                  "auditFlag": 0,
                  "commentAuditFlag": 0,
                  "domainName": null,
                  "templateIds": "",
                  "children": null,
                  "extFields": "[]",
                  "publishArticleFlag": 1,
                  "imortantFlag": 0,
                  "keywords": "",
                  "channelGrade": 0
                },
                {
                  "createTime": "2024-07-08 11:24:10",
                  "createUser": "吴斌",
                  "updateTime": "2024-07-08 11:24:10",
                  "updateUser": "吴斌",
                  "belongUserId": "1182830742988787712",
                  "belongDeptId": "1810140005514932226",
                  "tenantId": "7",
                  "channelId": "1810152871937376258",
                  "channelIcon": "",
                  "channelName": "pandayanking",
                  "channelCode": "0101",
                  "sortNum": 0,
                  "channelSummary": "",
                  "waterMarkImg": "",
                  "waterMarkLocation": "",
                  "waterMarkScale": 30,
                  "waterMarkAlpha": 100,
                  "parentChannelId": "1810152148695187457",
                  "parentChannelIds": "1810152148695187457",
                  "parentChannelNames": "TikTok",
                  "channelLevel": 1,
                  "extFieldsList": [],
                  "appId": "1384429363007430656",
                  "auditId": null,
                  "appShowFlag": 0,
                  "auditFlag": 0,
                  "commentAuditFlag": 0,
                  "domainName": null,
                  "templateIds": "",
                  "children": null,
                  "extFields": "[]",
                  "publishArticleFlag": 1,
                  "imortantFlag": 0,
                  "keywords": "",
                  "channelGrade": 0
                }
              ],
              "extFields": "[]",
              "publishArticleFlag": 1,
              "imortantFlag": 0,
              "keywords": "",
              "channelGrade": 0
            },
            {
              "createTime": "2024-07-08 10:20:03",
              "createUser": "王文博",
              "updateTime": "2024-07-08 10:20:03",
              "updateUser": "王文博",
              "belongUserId": "1384429363007430656",
              "belongDeptId": "1384429363007430656",
              "tenantId": "7",
              "channelId": "1810136737417199617",
              "channelIcon": "",
              "channelName": "测试栏目",
              "channelCode": "10",
              "sortNum": 0,
              "channelSummary": "",
              "waterMarkImg": "",
              "waterMarkLocation": "",
              "waterMarkScale": 30,
              "waterMarkAlpha": 100,
              "parentChannelId": "-1",
              "parentChannelIds": null,
              "parentChannelNames": null,
              "channelLevel": 0,
              "extFieldsList": [],
              "appId": "1384429363007430656",
              "auditId": null,
              "appShowFlag": 0,
              "auditFlag": 0,
              "commentAuditFlag": 0,
              "domainName": null,
              "templateIds": "",
              "children": null,
              "extFields": "[]",
              "publishArticleFlag": 1,
              "imortantFlag": 0,
              "keywords": "",
              "channelGrade": 0,
              "toggle":false,

            }
          ]
    )
    return{
        columList
    }
};